In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
stock_change = np.random.normal(0,1, (8,10))

In [5]:
stock_change

array([[-0.0115616 ,  0.77012907, -1.37138313,  0.06657027,  0.1462427 ,
        -1.75794634,  2.05954405,  0.03992356, -0.25009769,  0.13522856],
       [-0.69097921,  0.78077073,  0.09050113,  0.20989077,  2.06393737,
        -0.20560383, -0.693826  , -0.56202929,  1.53242952,  0.60647896],
       [-0.51187324,  0.22445395, -1.21474191, -1.54015467, -0.13703247,
         1.61048894,  0.65670623,  0.72897067, -2.26883328,  0.67543874],
       [-0.15843342,  2.07433281,  0.18602596,  0.95778058,  0.49626502,
         0.70247939, -0.1356852 ,  0.71768252, -0.42633265, -2.58527221],
       [ 0.77265746, -0.41040048, -1.15532313, -0.41096549, -1.5855577 ,
         1.68212244,  0.33959776,  0.80702657, -0.53815991,  0.49617391],
       [-0.57538992, -1.29590899, -0.75262765, -0.48821291,  1.35218437,
         1.34507978, -1.09890134, -0.15492003, -0.87954308, -1.38766405],
       [ 0.75426774,  0.31668194, -0.90695763,  0.35014866,  0.25825196,
         1.24702232,  0.67231402, -0.32019074

In [6]:
stock_change > 0.5

array([[False,  True, False, False, False, False,  True, False, False,
        False],
       [False,  True, False, False,  True, False, False, False,  True,
         True],
       [False, False, False, False, False,  True,  True,  True, False,
         True],
       [False,  True, False,  True, False,  True, False,  True, False,
        False],
       [ True, False, False, False, False,  True, False,  True, False,
        False],
       [False, False, False, False,  True,  True, False, False, False,
        False],
       [ True, False, False, False, False,  True,  True, False, False,
        False],
       [ True, False,  True,  True, False, False,  True,  True,  True,
        False]])

In [7]:
stock_change[stock_change > 0.5]

array([0.77012907, 2.05954405, 0.78077073, 2.06393737, 1.53242952,
       0.60647896, 1.61048894, 0.65670623, 0.72897067, 0.67543874,
       2.07433281, 0.95778058, 0.70247939, 0.71768252, 0.77265746,
       1.68212244, 0.80702657, 1.35218437, 1.34507978, 0.75426774,
       1.24702232, 0.67231402, 1.11539589, 0.77512581, 0.71048159,
       0.93159502, 2.30324292, 0.61453197])

In [8]:
stock_change[0:2, 0:5]

array([[-0.0115616 ,  0.77012907, -1.37138313,  0.06657027,  0.1462427 ],
       [-0.69097921,  0.78077073,  0.09050113,  0.20989077,  2.06393737]])

In [11]:
print(f'{stock_change[0:2, 0:5] > 0} ==> {np.all(stock_change[0:2, 0:5] > 0)}')

[[False  True False  True  True]
 [False  True  True  True  True]] ==> False


In [14]:
print(f'{stock_change[:5,:] > 0} ==> {np.any(stock_change[:5,] > 0)}')

[[False  True False  True  True False  True  True False  True]
 [False  True  True  True  True False False False  True  True]
 [False  True False False False  True  True  True False  True]
 [False  True  True  True  True  True False  True False False]
 [ True False False False False  True  True  True False  True]] ==> True


# np.where

In [15]:
temp = stock_change[:4,:4]

In [16]:
temp

array([[-0.0115616 ,  0.77012907, -1.37138313,  0.06657027],
       [-0.69097921,  0.78077073,  0.09050113,  0.20989077],
       [-0.51187324,  0.22445395, -1.21474191, -1.54015467],
       [-0.15843342,  2.07433281,  0.18602596,  0.95778058]])

In [17]:
np.where(temp > 0, 1, 0)

array([[0, 1, 0, 1],
       [0, 1, 1, 1],
       [0, 1, 0, 0],
       [0, 1, 1, 1]])

In [18]:
np.logical_and(temp > 0.5, temp < 1)

array([[False,  True, False, False],
       [False,  True, False, False],
       [False, False, False, False],
       [False, False, False,  True]])

In [19]:
np.where(np.logical_and(temp > 0.5, temp < 1), 1, 0)

array([[0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 1]])

In [21]:
np.where(np.logical_or(temp < -0.5, temp > 0.5), 1, 0)

array([[0, 1, 1, 0],
       [1, 1, 0, 0],
       [1, 0, 1, 1],
       [0, 1, 0, 1]])

# 统计最大涨幅

In [22]:
temp

array([[-0.0115616 ,  0.77012907, -1.37138313,  0.06657027],
       [-0.69097921,  0.78077073,  0.09050113,  0.20989077],
       [-0.51187324,  0.22445395, -1.21474191, -1.54015467],
       [-0.15843342,  2.07433281,  0.18602596,  0.95778058]])

In [24]:
temp.max(axis=0)

array([-0.0115616 ,  2.07433281,  0.18602596,  0.95778058])

In [25]:
temp.max(axis=1)

array([0.77012907, 0.78077073, 0.22445395, 2.07433281])

In [26]:
temp.max(axis=-1)

array([0.77012907, 0.78077073, 0.22445395, 2.07433281])

In [86]:
temp.var(axis=0)

array([0.07338094, 0.46272906, 0.51638126, 0.82862752])

In [28]:
temp.std(axis=0)

array([0.27088917, 0.68024192, 0.71859673, 0.9102898 ])

In [29]:
temp.mean(axis=0)

array([-0.34321187,  0.96242164, -0.57739949, -0.07647826])

In [30]:
np.argmin(temp, axis=0)

array([1, 2, 0, 2], dtype=int64)

In [31]:
data = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])

In [35]:
data.max(axis=2)

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [33]:
data.shape

(3, 2, 2)

In [36]:
data.max(axis=0)

array([[ 9, 10],
       [11, 12]])

In [37]:
data.max(axis=1)

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [38]:
np.argmax(data,axis=1)

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int64)

In [39]:
np.argmax(data,axis=2)

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int64)

# 数组与数的运算

In [40]:
data = np.array([[1,2,3,2,1,4], [5,6,1,2,3,1]])

In [41]:
data

array([[1, 2, 3, 2, 1, 4],
       [5, 6, 1, 2, 3, 1]])

In [42]:
data * 10

array([[10, 20, 30, 20, 10, 40],
       [50, 60, 10, 20, 30, 10]])

# 数组与数组的运算

In [43]:
data.shape

(2, 6)

In [44]:
data * np.array([1,2,3,4,5,6])

array([[ 1,  4,  9,  8,  5, 24],
       [ 5, 12,  3,  8, 15,  6]])

In [45]:
data * np.array([[1,2,3,4,5,6],[2,2,2,2,2,2]])

array([[ 1,  4,  9,  8,  5, 24],
       [10, 12,  2,  4,  6,  2]])

# 矩阵运算

矩阵是2维数组。
矩阵和2维数组 - 

In [46]:
score = np.array([[80,86],[82,80],[85,78],[90,90],[86,82],[82,90],[78,80],[92,94]])

In [47]:
score

array([[80, 86],
       [82, 80],
       [85, 78],
       [90, 90],
       [86, 82],
       [82, 90],
       [78, 80],
       [92, 94]])

In [48]:
np.mat(score)

matrix([[80, 86],
        [82, 80],
        [85, 78],
        [90, 90],
        [86, 82],
        [82, 90],
        [78, 80],
        [92, 94]])

In [49]:
np.mat([[80, 86],
       [82, 80],
       [85, 78],
       [90, 90],
       [86, 82],
       [82, 90],
       [78, 80],
       [92, 94]])

matrix([[80, 86],
        [82, 80],
        [85, 78],
        [90, 90],
        [86, 82],
        [82, 90],
        [78, 80],
        [92, 94]])

In [50]:
type(score)

numpy.ndarray

In [52]:
type(np.mat([[80, 86],
       [82, 80],
       [85, 78],
       [90, 90],
       [86, 82],
       [82, 90],
       [78, 80],
       [92, 94]]))

numpy.matrix

In [56]:
# (8,2) * (2,1) = (8,1)
np.mat(score)* np.array([[0.7],[0.3]])

matrix([[81.8],
        [81.4],
        [82.9],
        [90. ],
        [84.8],
        [84.4],
        [78.6],
        [92.6]])

In [58]:
np.matmul(score, np.array([[0.7],[0.3]]))

array([[81.8],
       [81.4],
       [82.9],
       [90. ],
       [84.8],
       [84.4],
       [78.6],
       [92.6]])

In [59]:
np.dot(score, np.array([[0.7],[0.3]]))

array([[81.8],
       [81.4],
       [82.9],
       [90. ],
       [84.8],
       [84.4],
       [78.6],
       [92.6]])

In [60]:
score @ np.array([[0.7],[0.3]])

array([[81.8],
       [81.4],
       [82.9],
       [90. ],
       [84.8],
       [84.4],
       [78.6],
       [92.6]])

In [61]:
score * np.mat(np.array([[0.7],[0.3]]))

matrix([[81.8],
        [81.4],
        [82.9],
        [90. ],
        [84.8],
        [84.4],
        [78.6],
        [92.6]])

# 数组合并

In [64]:
a = stock_change[:2, 0:4]
b = stock_change[3:5, 0:4]

In [65]:
a

array([[-0.0115616 ,  0.77012907, -1.37138313,  0.06657027],
       [-0.69097921,  0.78077073,  0.09050113,  0.20989077]])

In [67]:
b

array([[-0.15843342,  2.07433281,  0.18602596,  0.95778058],
       [ 0.77265746, -0.41040048, -1.15532313, -0.41096549]])

In [68]:
np.hstack((a,b))

array([[-0.0115616 ,  0.77012907, -1.37138313,  0.06657027, -0.15843342,
         2.07433281,  0.18602596,  0.95778058],
       [-0.69097921,  0.78077073,  0.09050113,  0.20989077,  0.77265746,
        -0.41040048, -1.15532313, -0.41096549]])

In [69]:
np.vstack((a,b))

array([[-0.0115616 ,  0.77012907, -1.37138313,  0.06657027],
       [-0.69097921,  0.78077073,  0.09050113,  0.20989077],
       [-0.15843342,  2.07433281,  0.18602596,  0.95778058],
       [ 0.77265746, -0.41040048, -1.15532313, -0.41096549]])

In [70]:
np.concatenate((a,b))

array([[-0.0115616 ,  0.77012907, -1.37138313,  0.06657027],
       [-0.69097921,  0.78077073,  0.09050113,  0.20989077],
       [-0.15843342,  2.07433281,  0.18602596,  0.95778058],
       [ 0.77265746, -0.41040048, -1.15532313, -0.41096549]])

In [71]:
np.concatenate((a,b), axis=0)

array([[-0.0115616 ,  0.77012907, -1.37138313,  0.06657027],
       [-0.69097921,  0.78077073,  0.09050113,  0.20989077],
       [-0.15843342,  2.07433281,  0.18602596,  0.95778058],
       [ 0.77265746, -0.41040048, -1.15532313, -0.41096549]])

In [72]:
np.concatenate((a,b), axis=1)

array([[-0.0115616 ,  0.77012907, -1.37138313,  0.06657027, -0.15843342,
         2.07433281,  0.18602596,  0.95778058],
       [-0.69097921,  0.78077073,  0.09050113,  0.20989077,  0.77265746,
        -0.41040048, -1.15532313, -0.41096549]])

# 数组的分割

In [73]:
x = np.arange(20)

In [74]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [75]:
np.split(x, 5)

[array([0, 1, 2, 3]),
 array([4, 5, 6, 7]),
 array([ 8,  9, 10, 11]),
 array([12, 13, 14, 15]),
 array([16, 17, 18, 19])]

In [80]:
x = np.arange(0,20,2)

In [81]:
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [82]:
np.split(x,[3,5,9])

[array([0, 2, 4]), array([6, 8]), array([10, 12, 14, 16]), array([18])]

In [83]:
x = np.arange(0,20,2)
np.split(x,[3,5,9,10])

[array([0, 2, 4]),
 array([6, 8]),
 array([10, 12, 14, 16]),
 array([18]),
 array([], dtype=int32)]

# 数据IO

In [85]:
np.genfromtxt("weather-for-cities.csv", delimiter=",")

array([[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan,  5., 12., 22., 23., 10., 15., 18., 16.,  3.,  8.],
       [nan,  4., 13., 23., 24., 11., 16., 19., 17.,  4.,  9.],
       [nan,  3., 14., 24., 25., 12., 17., 20., 18.,  5., 10.],
       [nan,  6., 15., 25., 26., 13., 18., 21., 19.,  6., 11.],
       [nan,  7., 16., 26., 27., 14., 19., 22., 20.,  7., 12.],
       [nan,  8., 17., 27., 28., 15., 20., 23., 21.,  8., 13.],
       [nan,  9., 18., 28., 29., 16., 21., 24., 22.,  9., 14.],
       [nan, 10., 19., 29., 30., 17., 22., 25., 23., 10., 15.],
       [nan, 11., 20., 30., 31., 18., 23., 26., 24., 11., 16.],
       [nan, 12., 21., 31., 32., 19., 24., 27., 25., 12., 17.],
       [nan, 13., 22., 32., 33., 20., 25., 28., 26., 13., 18.],
       [nan, 14., 23., 33., 34., 21., 26., 29., 27., 14., 19.],
       [nan, 15., 24., 34., 35., 22., 27., 30., 28., 15., 20.],
       [nan, 16., 25., 35., 36., 23., 28., 31., 29., 16., 21.]])